# Generated by Django 2.1.4 on 2019-01-13 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Openbook', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(max_length=200),
        ),
    ]
